name: Docker Image CI

on:
  push:
    branches: [ "1.2.0" ]
  pull_request:
    branches: [ "1.2.0" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rustdesk-kasm-image:1.2.0
